version: '3'

tasks:
  build:
    dir: ./fns/get-artwork
    sources:
      - ./**/*.go
    cmds:
      - go build -ldflags='-s -w' -o ./.bin/bootstrap ./cmd/handler/...
  deploy:
    sources:
      - ./fns/*/.bin/bootstrap
    deps:
      - build
    cmds:
      - terraform apply -auto-approve
